# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.CharField(max_length=255, verbose_name='Jazz Album')),
                ('artist', models.CharField(blank=True, max_length=255, verbose_name='Artist')),
                ('year', models.IntegerField(blank=True, max_length=4, verbose_name='Year')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cms.Record', verbose_name='Album')),
            ],
        ),
    ]
